# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:17
EXPOSE 8081
COPY --from=build /app/target/tour-package-service.jar tour-package-service-spb.jar
ENTRYPOINT ["java", "-jar", "tour-package-service-spb.jar"]
