version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tourdb
      MYSQL_USER: touruser
      MYSQL_PASSWORD: tourpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  tour-package-service:
    image: souriish9/tour-package-services:latest
    container_name: tour-package-service
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: tourdb
      DB_USER: touruser
      DB_PASSWORD: tourpass

volumes:
  mysql_data:
