version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: touruser
      POSTGRES_PASSWORD: tourpass
      POSTGRES_DB: tourdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U touruser -d tourdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  tour-package-service:
    image: souriish9/tour-package-services:latest
    container_name: tour-package-service
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: tourdb
      DB_USER: touruser
      DB_PASSWORD: tourpass

volumes:
  postgres_data: